package cn.bugstack.domain.admin.discount;

import cn.bugstack.api.dto.discount.DiscountCreateRequestDTO;
import cn.bugstack.api.dto.discount.DiscountResponseDTO;
import cn.bugstack.api.dto.discount.DiscountUpdateRequestDTO;
import cn.bugstack.api.response.Response;
import cn.bugstack.domain.admin.discount.model.entity.GroupBuyDiscountEntity;
import cn.bugstack.domain.admin.discount.repository.IDiscountRepository;
import cn.bugstack.types.enums.ResponseCode;
import lombok.extern.slf4j.Slf4j;
import org.apache.commons.lang3.RandomStringUtils;
import org.apache.commons.lang3.StringUtils;
import org.springframework.dao.DuplicateKeyException;
import org.springframework.stereotype.Service;

import javax.annotation.Resource;
import java.util.Date;
import java.util.List;
import java.util.stream.Collectors;

@Slf4j
@Service
public class DiscountService implements IDiscountService {

    @Resource
    private IDiscountRepository discountRepository;

    @Override
    public Response<String> createDiscount(DiscountCreateRequestDTO requestDTO) {
        try {
            if (requestDTO == null
                    || StringUtils.isBlank(requestDTO.getDiscountName())
                    || StringUtils.isBlank(requestDTO.getDiscountDesc())
                    || requestDTO.getDiscountType() == null
                    || StringUtils.isBlank(requestDTO.getMarketPlan())
                    || StringUtils.isBlank(requestDTO.getMarketExpr())) {
                return Response.<String>builder()
                        .code(ResponseCode.ILLEGAL_PARAMETER.getCode())
                        .info(ResponseCode.ILLEGAL_PARAMETER.getInfo())
                        .build();
            }

            String discountId = requestDTO.getDiscountId();
            boolean autoGenerateDiscountId = StringUtils.isBlank(discountId);
            if (autoGenerateDiscountId) {
                discountId = RandomStringUtils.randomNumeric(8);
            }

            GroupBuyDiscountEntity entity = GroupBuyDiscountEntity.builder()
                    .discountId(discountId)
                    .discountName(requestDTO.getDiscountName())
                    .discountDesc(requestDTO.getDiscountDesc())
                    .discountType(requestDTO.getDiscountType())
                    .marketPlan(requestDTO.getMarketPlan())
                    .marketExpr(requestDTO.getMarketExpr())
                    .tagId(requestDTO.getTagId())
                    .createTime(new Date())
                    .updateTime(new Date())
                    .build();

            try {
                discountRepository.insertDiscount(entity);
            } catch (DuplicateKeyException e) {
                if (autoGenerateDiscountId) {
                    discountId = RandomStringUtils.randomNumeric(8);
                    entity.setDiscountId(discountId);
                    discountRepository.insertDiscount(entity);
                } else {
                    throw e;
                }
            }

            return Response.<String>builder()
                    .code(ResponseCode.SUCCESS.getCode())
                    .info(ResponseCode.SUCCESS.getInfo())
                    .data(discountId)
                    .build();
        } catch (Exception e) {
            log.error("创建折扣失败 req:{}", requestDTO, e);
            return Response.<String>builder()
                    .code(ResponseCode.UN_ERROR.getCode())
                    .info(ResponseCode.UN_ERROR.getInfo())
                    .build();
        }
    }

    @Override
    public Response<Boolean> updateDiscount(String discountId, DiscountUpdateRequestDTO requestDTO) {
        try {
            if (StringUtils.isBlank(discountId) || requestDTO == null) {
                return Response.<Boolean>builder()
                        .code(ResponseCode.ILLEGAL_PARAMETER.getCode())
                        .info(ResponseCode.ILLEGAL_PARAMETER.getInfo())
                        .data(Boolean.FALSE)
                        .build();
            }

            boolean updateSuccess = discountRepository.updateDiscount(GroupBuyDiscountEntity.builder()
                    .discountId(discountId)
                    .discountName(requestDTO.getDiscountName())
                    .discountDesc(requestDTO.getDiscountDesc())
                    .discountType(requestDTO.getDiscountType())
                    .marketPlan(requestDTO.getMarketPlan())
                    .marketExpr(requestDTO.getMarketExpr())
                    .tagId(requestDTO.getTagId())
                    .updateTime(new Date())
                    .build());

            if (!updateSuccess) {
                return Response.<Boolean>builder()
                        .code(ResponseCode.UPDATE_ZERO.getCode())
                        .info(ResponseCode.UPDATE_ZERO.getInfo())
                        .data(Boolean.FALSE)
                        .build();
            }

            return Response.<Boolean>builder()
                    .code(ResponseCode.SUCCESS.getCode())
                    .info(ResponseCode.SUCCESS.getInfo())
                    .data(Boolean.TRUE)
                    .build();
        } catch (Exception e) {
            log.error("更新折扣失败 discountId:{} req:{}", discountId, requestDTO, e);
            return Response.<Boolean>builder()
                    .code(ResponseCode.UN_ERROR.getCode())
                    .info(ResponseCode.UN_ERROR.getInfo())
                    .data(Boolean.FALSE)
                    .build();
        }
    }

    @Override
    public Response<Boolean> deleteDiscount(String discountId) {
        try {
            if (StringUtils.isBlank(discountId)) {
                return Response.<Boolean>builder()
                        .code(ResponseCode.ILLEGAL_PARAMETER.getCode())
                        .info(ResponseCode.ILLEGAL_PARAMETER.getInfo())
                        .data(Boolean.FALSE)
                        .build();
            }

            boolean deleteSuccess = discountRepository.deleteDiscount(discountId);
            if (!deleteSuccess) {
                return Response.<Boolean>builder()
                        .code(ResponseCode.UPDATE_ZERO.getCode())
                        .info(ResponseCode.UPDATE_ZERO.getInfo())
                        .data(Boolean.FALSE)
                        .build();
            }

            return Response.<Boolean>builder()
                    .code(ResponseCode.SUCCESS.getCode())
                    .info(ResponseCode.SUCCESS.getInfo())
                    .data(Boolean.TRUE)
                    .build();
        } catch (Exception e) {
            log.error("删除折扣失败 discountId:{}", discountId, e);
            return Response.<Boolean>builder()
                    .code(ResponseCode.UN_ERROR.getCode())
                    .info(ResponseCode.UN_ERROR.getInfo())
                    .data(Boolean.FALSE)
                    .build();
        }
    }

    @Override
    public Response<DiscountResponseDTO> queryDiscount(String discountId) {
        try {
            if (StringUtils.isBlank(discountId)) {
                return Response.<DiscountResponseDTO>builder()
                        .code(ResponseCode.ILLEGAL_PARAMETER.getCode())
                        .info(ResponseCode.ILLEGAL_PARAMETER.getInfo())
                        .build();
            }

            DiscountResponseDTO dto = toDTO(discountRepository.queryDiscount(discountId));
            return Response.<DiscountResponseDTO>builder()
                    .code(ResponseCode.SUCCESS.getCode())
                    .info(ResponseCode.SUCCESS.getInfo())
                    .data(dto)
                    .build();
        } catch (Exception e) {
            log.error("查询折扣失败 discountId:{}", discountId, e);
            return Response.<DiscountResponseDTO>builder()
                    .code(ResponseCode.UN_ERROR.getCode())
                    .info(ResponseCode.UN_ERROR.getInfo())
                    .build();
        }
    }

    @Override
    public Response<List<DiscountResponseDTO>> queryDiscountList() {
        try {
            List<GroupBuyDiscountEntity> list = discountRepository.queryDiscountList();
            List<DiscountResponseDTO> dtoList = list.stream().map(this::toDTO).collect(Collectors.toList());
            return Response.<List<DiscountResponseDTO>>builder()
                    .code(ResponseCode.SUCCESS.getCode())
                    .info(ResponseCode.SUCCESS.getInfo())
                    .data(dtoList)
                    .build();
        } catch (Exception e) {
            log.error("查询折扣列表失败", e);
            return Response.<List<DiscountResponseDTO>>builder()
                    .code(ResponseCode.UN_ERROR.getCode())
                    .info(ResponseCode.UN_ERROR.getInfo())
                    .build();
        }
    }

    private DiscountResponseDTO toDTO(GroupBuyDiscountEntity entity) {
        if (entity == null) return null;
        return DiscountResponseDTO.builder()
                .id(entity.getId())
                .discountId(entity.getDiscountId())
                .discountName(entity.getDiscountName())
                .discountDesc(entity.getDiscountDesc())
                .discountType(entity.getDiscountType())
                .marketPlan(entity.getMarketPlan())
                .marketExpr(entity.getMarketExpr())
                .tagId(entity.getTagId())
                .createTime(entity.getCreateTime())
                .updateTime(entity.getUpdateTime())
                .build();
    }
}
